In [2]:
A = [2.0 4 -2; 4 9 -3; -2 -3 7]

3×3 Array{Float64,2}:
  2.0   4.0  -2.0
  4.0   9.0  -3.0
 -2.0  -3.0   7.0

In [3]:
using LinearAlgebra

In [4]:
x = A\b # <- solves the system

UndefVarError: UndefVarError: b not defined

# A = LU

In [5]:
rank(A)

3

In [8]:
ℓ_21 = -A[2,1]/A[1,1]
E_21 = [1 0 0; ℓ_21 1 0; 0 0 1]

3×3 Array{Float64,2}:
  1.0  0.0  0.0
 -2.0  1.0  0.0
  0.0  0.0  1.0

In [9]:
E_21*A

3×3 Array{Float64,2}:
  2.0   4.0  -2.0
  0.0   1.0   1.0
 -2.0  -3.0   7.0

In [13]:
function E(i,j, A)
    ℓ_ij = -A[i, j]/A[j,j]
    E_ij = Matrix{Float64}(I, size(A)[1], size(A)[1])
    E_ij[i,j] = ℓ_ij
    return E_ij
end
# make sure i != j

E (generic function with 2 methods)

In [8]:
A

3×3 Array{Float64,2}:
  2.0   4.0  -2.0
  4.0   9.0  -3.0
 -2.0  -3.0   7.0

In [20]:
for i = 2:size(A)[1]
    U = E(i, 1, A)*A
end

In [18]:
A

3×3 Array{Float64,2}:
 2.0  4.0  -2.0
 0.0  1.0   1.0
 0.0  1.0   5.0

In [22]:
U = E(2,1,A)*A
U = E(3,1,U)*U
U = E(3,2,U)*U

3×3 Array{Float64,2}:
 2.0  4.0  -2.0
 0.0  1.0   1.0
 0.0  0.0   4.0