In [62]:
using LinearAlgebra

function lu_decomposition(A)
    m = size(A)[1]
    L = Matrix{Float64}(I,m,m)
    U = copy(A)
    for k = 1:m-1
        for j = k+1:m
            L[j,k] = U[j,k]/U[k,k]
            U[j,k:m] = U[j,k:m]-L[j,k]*U[k,k:m]
        end
    end
    return L, U
end

lu_decomposition (generic function with 1 method)

In [55]:
A = [2.0 1 1 0; 4 3 3 1; 8 7 9 5; 6 7 9 8]

4×4 Array{Float64,2}:
 2.0  1.0  1.0  0.0
 4.0  3.0  3.0  1.0
 8.0  7.0  9.0  5.0
 6.0  7.0  9.0  8.0

In [65]:
L, U = lu_decomposition(A)


([1.0 0.0 0.0 0.0; 2.0 1.0 0.0 0.0; 4.0 3.0 1.0 0.0; 3.0 4.0 1.0 1.0], [2.0 1.0 1.0 0.0; 0.0 1.0 1.0 1.0; 0.0 0.0 2.0 2.0; 0.0 0.0 0.0 2.0])

In [66]:
U

4×4 Array{Float64,2}:
 2.0  1.0  1.0  0.0
 0.0  1.0  1.0  1.0
 0.0  0.0  2.0  2.0
 0.0  0.0  0.0  2.0

In [12]:
using LinearAlgebra

In [16]:
L = Matrix{Float64}(I,size(A)[1],size(A)[2])

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [46]:
U

UndefVarError: UndefVarError: U not defined

In [67]:
U = copy(A)
U

4×4 Array{Float64,2}:
 2.0  1.0  1.0  0.0
 4.0  3.0  3.0  1.0
 8.0  7.0  9.0  5.0
 6.0  7.0  9.0  8.0

In [68]:
norm(A - L*U)

53.028294334251406

In [69]:
function forward_solve(L, b)
    m = size(L)[1]
    c = zeros(size(L)[1])
    c[1] = b[1]/L[1,1]
    
    for k = 2:m
        c[k] = (b[k] - (sum([L[k,i]*c[i] for i = 1:k-1])))/L[k,k]
    end
    return c
end

forward_solve (generic function with 1 method)

In [70]:
function back_solve(U,b)
    m = size(U)[1]
    x = zeros(m)
    x[m] = b[m]/U[m,m]
    
    for k = m-1:-1:1
        x[k] = (b[k] - (sum([U[k,i]*x[i] for i = k+1:m])))/U[k,k]
    end
    
    return x
end

back_solve (generic function with 1 method)

In [71]:
function solve_system(A,b)
    L,U = LU(A)
    c = forward_solve(L,b)
    x = back_solve(U,c)
    return x
end

solve_system (generic function with 1 method)

In [72]:
A = rand(1000,1000)
b = rand(1000)

1000-element Array{Float64,1}:
 0.011786262085748067
 0.1510242648299942  
 0.7853823230271242  
 0.5715894428662909  
 0.6733034665569197  
 0.9862437066345631  
 0.9343592116868751  
 0.04997934946965632 
 0.3689317633664482  
 0.08315305738990353 
 0.3405044718632897  
 0.4535425740934931  
 0.1051506395417996  
 ⋮                   
 0.26137999532558576 
 0.6672161575396987  
 0.19295420215136194 
 0.25780299360146897 
 0.19127437004996772 
 0.7482022235196946  
 0.19440340584967575 
 0.38008828799605143 
 0.5957720822485162  
 0.9820310996467705  
 0.6443116624561529  
 0.42047513039166207 

In [73]:
solve_system(A,b)

MethodError: MethodError: no method matching LU(::Array{Float64,2})
Closest candidates are:
  LU(::AbstractArray{T,2}, !Matched::Array{Int64,1}, !Matched::Int64) where T at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/lu.jl:17