In [73]:
using LinearAlgebra

In [75]:
A = rand(4,4)

4×4 Array{Float64,2}:
 0.857758  0.639799  0.417249   0.606661 
 0.478961  0.45981   0.0588546  0.97365  
 0.707149  0.688603  0.604962   0.0408288
 0.222945  0.754015  0.644346   0.728247 

In [18]:
ℓ = -A[2,1]/A[1,1]

-0.5348441450813093

In [74]:
E = Matrix{Float64}(I,4,4)

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [19]:
E[2,1] = ℓ

-0.5348441450813093

In [20]:
E*A

4×4 Array{Float64,2}:
 0.665095  0.168725   0.281339  0.633129 
 0.0       0.116502  -0.107291  0.032188 
 0.976449  0.71181    0.102501  0.0123133
 0.811404  0.456573   0.85091   0.890947 

In [15]:
ℓ_21 = -A[2,1]/A[1,1]
E_21 = Matrix{Float64}(I,4,4)
E_21[2,1] = ℓ_21

ℓ_31 = -A[3,1]/A[1,1]
E_31 = Matrix{Float64}(I,4,4)
E_31[3,1] = ℓ_31

ℓ_41 = -A[4,1]/A[1,1]
E_41 = Matrix{Float64}(I,4,4)
E_41[4,1] = ℓ_41

E_41*E_31*E_21*A

4×4 Array{Float64,2}:
  0.0126379      0.94443    0.444294    0.486464
  1.11022e-16  -68.3715   -31.4468    -34.5815  
 -1.11022e-16  -73.3019   -33.7655    -37.3022  
  0.0          -37.8893   -17.0672    -19.6072  

In [76]:
function zero_column(j,A)
    U = A
    n = size(A)[1]
    for i = j+1:n
        ℓ_ij = -A[i,j]/A[j,j]
        E_ij = Matrix{Float64}(I,n,n)
        E_ij[i,j] = ℓ_ij
        
        U = E_ij*U
    end
    
    return U
end

zero_column (generic function with 1 method)

In [77]:
U = zero_column(1,A)

4×4 Array{Float64,2}:
  0.857758     0.639799   0.417249   0.606661
 -5.55112e-17  0.102555  -0.174132   0.634898
  0.0          0.161142   0.260976  -0.459312
  0.0          0.587721   0.535897   0.570566

In [21]:
U = zero_column(2,U)

4×4 Array{Float64,2}:
  0.0126379      0.94443    0.444294     0.486464
  1.11022e-16  -68.3715   -31.4468     -34.5815  
 -2.30051e-16    0.0       -0.0510124   -0.226915
 -6.1525e-17     0.0        0.35958     -0.443216

In [22]:
zero_column(3,U)

4×4 Array{Float64,2}:
  0.0126379      0.94443    0.444294     0.486464
  1.11022e-16  -68.3715   -31.4468     -34.5815  
 -2.30051e-16    0.0       -0.0510124   -0.226915
 -1.68312e-15    0.0        0.0         -2.04271 

In [78]:
function upper_form(A)
    n = size(A)[1]
    U = A
    for i  = 1:n-1
        U = zero_column(i,U)
    end
    return U
end

upper_form (generic function with 1 method)

In [79]:
upper_form(A)

4×4 Array{Float64,2}:
  0.857758     0.639799   0.417249   0.606661
 -5.55112e-17  0.102555  -0.174132   0.634898
  8.72235e-17  0.0        0.534585  -1.45691 
  6.78651e-17  0.0        0.0        1.11221 

In [25]:
C = rand(10,10)
upper_form(C)

10×10 Array{Float64,2}:
 0.1692   0.00780022    0.126344      0.904869  …    0.0214114   0.185474   
 0.0      0.780885      0.485049     -2.17455        0.0374157   0.218055   
 0.0      0.0           0.332244     -0.619901       0.5196     -0.573663   
 0.0      0.0           0.0          -2.55308        2.22658    -1.92574    
 0.0      5.55112e-17   0.0           0.0           -0.266707   -0.0662093  
 0.0      2.25171e-15   0.0           0.0       …  -12.1687     -1.2546     
 0.0     -3.89499e-17   3.46945e-18   0.0            0.915176    0.337073   
 0.0     -3.67898e-16  -2.32548e-17   0.0            4.48562     0.491096   
 0.0      3.70462e-17  -1.10545e-16   0.0            4.53814     0.000418946
 0.0      2.65191e-17  -6.33617e-18   0.0            0.0        -0.387058   

In [35]:
U = [2.0 3 4 5; 0 3 10 1; 0 0 4 5; 0 0 0 8]
b = [1.0, 2, 3, 4]
x = zeros(4)

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

In [30]:
U\b

4-element Array{Float64,1}:
 -1.125              
  0.08333333333333333
  0.125              
  0.5                

In [31]:
function back_solve(U, b)
    n = size(U)[1]
    x = zeros(n)
    x[n] = b[n]/U[n,n]
    for k = n-1:-1:1
        x[k] = (b[k] - sum(U[k,:]*x))/U[k,k]
    end
    return x
end

back_solve (generic function with 1 method)

In [34]:
x = back_solve(U,b)

MethodError: MethodError: no method matching *(::Array{Float64,1}, ::Array{Float64,1})
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:502
  *(!Matched::Adjoint{#s576,#s575} where #s575<:Union{DenseArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2}, ReinterpretArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, ReshapedArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, SubArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, AbstractCartesianIndex},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}} where #s576, ::Union{DenseArray{S,1}, ReinterpretArray{S,1,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, ReshapedArray{S,1,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, SubArray{S,1,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, AbstractCartesianIndex},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}}) where {T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64}, S} at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/matmul.jl:98
  *(!Matched::Adjoint{#s576,#s575} where #s575<:LinearAlgebra.AbstractTriangular where #s576, ::AbstractArray{T,1} where T) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/triangular.jl:1805
  ...

In [36]:
x[4] = b[4]/U[4,4]

0.5

In [38]:
function back_solve(U, b)
    n = size(U)[1]
    x = zeros(n)
    x[n] = b[n]/U[n,n]
    for k = n-1:-1:1
        x[k] = (b[k] - sum([U[k,i]*x[i] for i = k+1:n]))/U[k,k]
    end
    return x
end

back_solve (generic function with 1 method)

In [39]:
back_solve(U,b)

4-element Array{Float64,1}:
 -1.125              
  0.08333333333333333
  0.125              
  0.5                

In [68]:
function L_matrix(A)
    n = size(A)
    for j in range(n)
        for i in range(j+1)
            x = sum()
        

inv_column (generic function with 1 method)